import { SearchProvider } from '../domain/provider';

export const DEFAULT_PROVIDERS: SearchProvider[] = [
  {
    id: 'google',
    name: 'Google',
    searchUrlTemplate: 'https://www.google.com/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'bing',
    name: 'Bing',
    searchUrlTemplate: 'https://www.bing.com/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'duckduckgo',
    name: 'DuckDuckGo',
    searchUrlTemplate: 'https://duckduckgo.com/?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'brave',
    name: 'Brave Search',
    searchUrlTemplate: 'https://search.brave.com/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'yahoo',
    name: 'Yahoo',
    searchUrlTemplate: 'https://search.yahoo.com/search?p={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'ask',
    name: 'Ask',
    searchUrlTemplate: 'https://www.ask.com/web?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'aol',
    name: 'AOL',
    searchUrlTemplate: 'https://search.aol.com/aol/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'startpage',
    name: 'Startpage',
    searchUrlTemplate: 'https://www.startpage.com/sp/search?query={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'qwant',
    name: 'Qwant',
    searchUrlTemplate: 'https://www.qwant.com/?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'mojeek',
    name: 'Mojeek',
    searchUrlTemplate: 'https://www.mojeek.com/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'swisscows',
    name: 'Swisscows',
    searchUrlTemplate: 'https://swisscows.com/en/web?query={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'metager',
    name: 'MetaGer',
    searchUrlTemplate: 'https://metager.org/meta/meta.ger3?eingabe={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'presearch',
    name: 'Presearch',
    searchUrlTemplate: 'https://presearch.com/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'yep',
    name: 'Yep',
    searchUrlTemplate: 'https://yep.com/web?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'searxng',
    name: 'SearXNG',
    searchUrlTemplate: 'https://searx.space/?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    searchUrlTemplate: 'https://www.perplexity.ai/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'you',
    name: 'You.com',
    searchUrlTemplate: 'https://you.com/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'kagi',
    name: 'Kagi',
    searchUrlTemplate: 'https://kagi.com/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'yandex',
    name: 'Yandex',
    searchUrlTemplate: 'https://yandex.com/search/?text={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'baidu',
    name: 'Baidu',
    searchUrlTemplate: 'https://www.baidu.com/s?wd={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'google-scholar',
    name: 'Google Scholar',
    searchUrlTemplate: 'https://scholar.google.com/scholar?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'semantic-scholar',
    name: 'Semantic Scholar',
    searchUrlTemplate: 'https://www.semanticscholar.org/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'ecosia',
    name: 'Ecosia',
    searchUrlTemplate: 'https://www.ecosia.org/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    searchUrlTemplate: 'https://www.youtube.com/results?search_query={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
  {
    id: 'github',
    name: 'GitHub',
    searchUrlTemplate: 'https://github.com/search?q={searchTerms}',
    enabled: true,
    isBuiltIn: true,
  },
];
